### ISSUE TITLE
Set up file structure

### ISSUE THREAD

**Issue by maxgerber** [MAM-Apps/MAM-Events#8]
1. Create a `public` folder, containing:
- [x] `index.html`
- [x] `style.css`
- [x] `normalize.css`
- [x] `assets` folder, containing:
    - [x] `favicon.ico`

2. Create a `src` folder, containing:
- [x] `model` folder, containing:
    - [x] `db_connection.js`
- [x] `views` folder, containing:
     - [x] `layouts` folder, containing:
          - [x] `main.hbs`
          - [x] `error.hbs`
     - [x] `partials` folder

- [x] `controller` folder, containing:
    - [x] `error.js`
    - [x] `index.js`

- [x] `app.js`
- [x] `index.js`

3. Create a `tests` folder:
- [x] `public.test.js`
- [x] `src.test.js`
- [x] `db.test.js`

4. Create a `db` folder:
- [x] `db_build.js`
- [x] `db_build.sql`

5. Create ___ in the root folder:
- [x] `config.env`
- [x] `.gitignore`
- [x] `.eslintrc`

**Comment by AseelM** [comment]
ticked two things of the list:
 1- favicon.ico it is a file that we will store in assets once created.
 2- db files: purposefully left them out as we will decide later on what files are needed.

**Comment by maxgerber** [comment]
File structure set up
