### ISSUE TITLE
Install Node, and dependencies

### ISSUE THREAD

**Issue by maxgerber** [MAM-Apps/MAM-Events#9]
Dependencies are:
- [x] env2
- [x] body-parser
- [x] express
- [x] express-handlebars
- [x] serve-favicon
- [x] mongodb

Development Dependencies are:
- [x] eslint
- [x] tap-spec
- [x] tape
- [x] supertest
- [x] istanbul
- [x] nodemon

**Comment by AseelM** [comment]
MongoDB isn't getting installed maybe rest of team can try again when needed.

**Comment by maxgerber** [comment]
Dependencies installed and working successfully 👍
